// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mmcc.Bot.Database;

namespace Mmcc.Bot.Database.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20210325020120_AddTags")]
    partial class AddTags
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Mmcc.Bot.Database.Entities.MemberApplication", b =>
                {
                    b.Property<int>("MemberApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AppStatus")
                        .HasColumnType("int(1)");

                    b.Property<long>("AppTime")
                        .HasColumnType("bigint");

                    b.Property<ulong>("AuthorDiscordId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("AuthorDiscordName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MessageContent")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("MemberApplicationId");

                    b.HasIndex("AuthorDiscordId");

                    b.HasIndex("GuildId");

                    b.ToTable("MemberApplications");
                });

            modelBuilder.Entity("Mmcc.Bot.Database.Entities.ModerationAction", b =>
                {
                    b.Property<int>("ModerationActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Date")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExpiryDate")
                        .HasColumnType("bigint");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ModerationActionType")
                        .HasColumnType("int(1)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<ulong?>("UserDiscordId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("UserIgn")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("ModerationActionId");

                    b.HasIndex("ModerationActionType");

                    b.HasIndex("UserDiscordId");

                    b.HasIndex("UserIgn");

                    b.ToTable("ModerationActions");
                });

            modelBuilder.Entity("Mmcc.Bot.Database.Entities.Tag", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("TagName")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<ulong>("CreatedByDiscordId")
                        .HasColumnType("bigint unsigned");

                    b.Property<long?>("LastModifiedAt")
                        .HasColumnType("bigint");

                    b.Property<ulong?>("LastModifiedByDiscordId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("TagDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("GuildId", "TagName");

                    b.HasIndex("GuildId");

                    b.HasIndex("TagName");

                    b.ToTable("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
